// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXxX6Pi1o37cYl8iR8mW6CwxvbwV7Rq1Y',
    appId: '1:33210290917:web:12fb3edacb954986acfa0c',
    messagingSenderId: '33210290917',
    projectId: 'toko-novel',
    authDomain: 'toko-novel.firebaseapp.com',
    storageBucket: 'toko-novel.firebasestorage.app',
    measurementId: 'G-WYQBSX2LJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxxNKqazIgAm_b5Sk4Jjfn3ArlkcvZPo',
    appId: '1:33210290917:android:a730d86526ba9412acfa0c',
    messagingSenderId: '33210290917',
    projectId: 'toko-novel',
    storageBucket: 'toko-novel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6av2fRR5QYQm-QU5dtpPfphqefspZo-0',
    appId: '1:33210290917:ios:a7602e5024bf0f5bacfa0c',
    messagingSenderId: '33210290917',
    projectId: 'toko-novel',
    storageBucket: 'toko-novel.firebasestorage.app',
    iosBundleId: 'com.example.tokonovel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6av2fRR5QYQm-QU5dtpPfphqefspZo-0',
    appId: '1:33210290917:ios:a7602e5024bf0f5bacfa0c',
    messagingSenderId: '33210290917',
    projectId: 'toko-novel',
    storageBucket: 'toko-novel.firebasestorage.app',
    iosBundleId: 'com.example.tokonovel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXxX6Pi1o37cYl8iR8mW6CwxvbwV7Rq1Y',
    appId: '1:33210290917:web:c63817b0d1fa74f0acfa0c',
    messagingSenderId: '33210290917',
    projectId: 'toko-novel',
    authDomain: 'toko-novel.firebaseapp.com',
    storageBucket: 'toko-novel.firebasestorage.app',
    measurementId: 'G-C11LCDY4EZ',
  );
}
